import { StripeProduct } from "@/app/models/subscription/StripeProduct";
import { StripeFeature } from "@/app/models/subscription/StripeFeature";
import {
  BillingPeriod,
  PriceType,
} from "@/app/models/subscription/StripePrice";

export const defaultProducts: StripeProduct[] = [
  {
    stripeId: "",
    tier: 1,
    title: "Standard 🔥",
    description:
      "Lorem ipsum dolor sit amet consect etur adipisicing elit. Itaque amet indis perferendis blanditiis repellendus etur quidem assumenda.",
    prices: [
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Monthly,
        price: 9,
        currency: "usd",
        trialDays: 14,
        active: true,
      },
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Yearly,
        price: 50,
        currency: "usd",
        trialDays: 30,
        active: true,
        priceBefore: 60,
      },
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Monthly,
        price: 170,
        currency: "mxn",
        trialDays: 14,
        active: true,
      },
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Yearly,
        price: 1001,
        currency: "mxn",
        trialDays: 30,
        active: true,
      },
    ],
    features: [
      { key: "maxNumberOfUsers", value: "1", included: true },
      { key: "feature2", value: "", included: true },
      { key: "feature3", value: "", included: true },
      { key: "feature4", value: "", included: true },
      { key: "feature5", value: "", included: false },
    ],
    badge: "",
    active: true,
    maxUsers: 1,
  },
  {
    stripeId: "",
    tier: 2,
    title: "Enterprise 🚀",
    description:
      "Lorem ipsum dolor sit amet consect etur adipisicing elit. Itaque amet indis perferendis blanditiis repellendus etur quidem assumenda.",
    prices: [
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Monthly,
        price: 29,
        currency: "usd",
        trialDays: 0,
        product: undefined,
        active: true,
      },
      {
        stripeId: "",
        type: PriceType.Recurring,
        billingPeriod: BillingPeriod.Yearly,
        price: 290,
        currency: "usd",
        trialDays: 0,
        product: undefined,
        active: true,
      },
    ],
    features: [
      { key: "maxNumberOfUsers", value: "5", included: true },
      { key: "feature2", value: "", included: true },
      { key: "feature3", value: "", included: true },
      { key: "feature4", value: "", included: true },
      { key: "feature5", value: "", included: false },
    ],
    badge: "recommended",
    active: true,
    maxUsers: 5,
  },
  {
    stripeId: "",
    tier: 3,
    title: "Unlimited 🦄",
    description:
      "Lorem ipsum dolor sit amet consect etur adipisicing elit. Itaque amet indis perferendis blanditiis repellendus etur quidem assumenda.",
    prices: [
      {
        stripeId: "",
        type: PriceType.OneTime,
        billingPeriod: BillingPeriod.Once,
        price: 399,
        currency: "usd",
        trialDays: 0,
        product: undefined,
        active: true,
        priceBefore: 499,
      },
      {
        stripeId: "",
        type: PriceType.OneTime,
        billingPeriod: BillingPeriod.Once,
        price: 336,
        currency: "eur",
        trialDays: 0,
        product: undefined,
        active: true,
        priceBefore: 421,
      },
    ],
    features: [
      { key: "unlimitedUsers", value: "", included: true },
      { key: "feature2", value: "", included: true },
      { key: "feature3", value: "", included: true },
      { key: "feature4", value: "", included: true },
      { key: "feature5", value: "", included: true },
    ],
    badge: "",
    active: true,
    maxUsers: 0,
  },
];
